### ISSUE TITLE
Staff users have CRUD access on Room model

### ISSUE THREAD

**Issue by AgaToma** [AgaToma/lighthouse-bnb#10]
As a Staff user, I can create, update, delete rooms, so that B&B website stays up to date without needing to ask a developer or logging to admin panel

## Acceptance Criteria
- Admin user is able to create, update and delete rooms 

## Tasks
- [x] Create create room view & template for admin user
- [x] Create update room view & template for admin user
- [x] Create delete room view & template for admin user
