### ISSUE TITLE
Guest users can book a room

### ISSUE THREAD

**Issue by AgaToma** [AgaToma/lighthouse-bnb#12]
As a Guest, I can book a room, so that I can enjoy my stay

## Acceptance Criteria
- Booking functionality works	

## Tasks
- [x] Create Booking app
- [x] Create Booking model
- [x] Create Booking form
