### ISSUE TITLE
Home app

### ISSUE THREAD

**Issue by AgaToma** [AgaToma/lighthouse-bnb#21]
As a developer, I can use home url, so that I can confirm the project is running correctly

## Acceptance Criteria
- Home page basic skeleton is rendering correctly when running project	

## Tasks
- [x] Create base.html
- [x] Create home app
- [x] Extend base.html to index.html
