### ISSUE TITLE
Own booking management by guest users

### ISSUE THREAD

**Issue by AgaToma** [AgaToma/lighthouse-bnb#23]
As a guest, I can view, edit or delete my bookings, so that my plans can be flexible

## Acceptance Criteria
- Guest users have full CRUD on their bookings
- Guest users cannot access other guests' bookings
- 
## Tasks
- [ ] Guest users can view their bookings
- [ ] Guest users can edit their bookings
- [ ] Guest users can remove their bookings
