### ISSUE TITLE
Guest registration

### ISSUE THREAD

**Issue by AgaToma** [AgaToma/lighthouse-bnb#3]
As a Guest, I can register only with my email and password, so that I can make a booking

## Acceptance Criteria
- Guest is able to register to make a booking only with their email & password 

## Tasks
- [x] Create custom user model based on AbstractBaseUser model
- [x] Install Django allauth for user authentication 
- [x] Signup/register page
