### ISSUE TITLE
User password editing

### ISSUE THREAD

**Issue by AgaToma** [AgaToma/lighthouse-bnb#6]
As a User, I can reset my password, so that I can access my account if I forget the old password

## Acceptance Criteria
- Password reset functionality works	

## Tasks
- [x] Set up gmail
- [x] Set up Heroku config vars
- [x] Set up settings.py
