### ISSUE TITLE
Guest users can view rooms

### ISSUE THREAD

**Issue by AgaToma** [AgaToma/lighthouse-bnb#8]
As a User, I can view listed rooms, so that I can make my selection

## Acceptance Criteria
- Rooms are listed on a separate page
- Each room has a link directing to a detail page
	
## Tasks
- [x] Create Rooms app
- [x] Create Room model
- [x] Create a room list page
