### ISSUE TITLE
Guest users can view room details

### ISSUE THREAD

**Issue by AgaToma** [AgaToma/lighthouse-bnb#9]
As a User, I can see the details of the room, so that I can decide if I would book it

## Acceptance Criteria
- Room detail page displays when clicked
- All model details are shown on the page

## Tasks
- [x] Create room model
- [x] Create room detail page
- [x] Create test rooms from the model
